name: CI-CD Pipeline

on:
    push:
        branches:
            - main
            - 'feature/*'
    pull_request:
        branches:
            - main
    workflow_dispatch:


jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
            - uses: actions/checkout@v6
            - name: Log in to DockerHub
            - uses: docker/login-action@v6
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ vars.DOCKERHUB_PASSWORD }}
            - name: Build and push Docker image
            - with:
              context: .
              push: true
              tags: ${{ vars.DOCKERHUB_USERNAME }}/github_elt:latest